---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "loki"
    app: prometheus
  name: loki
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"