apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: ea4e0efdbdf1bc30b8c441a1f1e736b0fc5c006a950cc4c3f679a0c62833d974
    cni.projectcalico.org/podIP: 10.244.151.30/32
    cni.projectcalico.org/podIPs: 10.244.151.30/32
  creationTimestamp: "2022-08-02T11:09:29Z"
  generateName: mimir-6d54fdb9bc-
  labels:
    app: prometheus
    component: mimir
    pod-template-hash: 6d54fdb9bc
  name: mimir-6d54fdb9bc-95m8f
  namespace: observability
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mimir-6d54fdb9bc
    uid: 5d21ecc7-8184-424d-a34a-4453550f5d68
  resourceVersion: "55943"
  uid: 63fc5911-2622-40b0-a245-d3f062557344
spec:
  containers:
  - args:
    - -target=all,alertmanager,overrides-exporter
    - -config.expand-env=true
    - -config.file=/etc/mimir/mimir.yaml
    image: grafana/mimir:2.2.0
    imagePullPolicy: IfNotPresent
    name: mimir
    ports:
    - containerPort: 9009
      protocol: TCP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/mimir
      name: config-volume
    - mountPath: /var/mimir
      name: runtime-config
    - mountPath: /data
      name: storage-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-txfhk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube-m03
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: mimir
  serviceAccountName: mimir
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: mimir-config
    name: config-volume
  - configMap:
      defaultMode: 420
      name: mimir-runtime
    name: runtime-config
  - name: storage-volume
    persistentVolumeClaim:
      claimName: mimir
  - name: kube-api-access-txfhk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-08-02T11:09:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-08-02T11:09:29Z"
    message: 'containers with unready status: [mimir]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-08-02T11:09:29Z"
    message: 'containers with unready status: [mimir]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-08-02T11:09:29Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b182456c7c3eae61eebdc76e7e62f777576ea893a162632d81a9df4031649fd9
    image: grafana/mimir:2.2.0
    imageID: docker-pullable://grafana/mimir@sha256:22a3fd7fcdea01623aa22f30a2c2cc9c397b1a117cfc43e163b98593a0778336
    lastState: {}
    name: mimir
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-08-02T11:10:08Z"
  hostIP: 192.168.49.4
  phase: Running
  podIP: 10.244.151.30
  podIPs:
  - ip: 10.244.151.30
  qosClass: Burstable
  startTime: "2022-08-02T11:09:29Z"
